fig,axs=plt.subplots()
axs.axis('equal')
plt.plot([0,1,1,0,0],[0,0,1,1,0], linewidth=3, label='random diagonal')
plt.plot([0,F_r[0,0],F_r[0,0]+F_r[0,1],F_r[0,1],0],[0,F_r[1,0],F_r[1,0]+F_r[1,1],F_r[1,1],0], linewidth=2, label='random diagonal', linestyle='--')
plt.plot([0,F_rdv[0,0],F_rdv[0,0]+F_rdv[0,1],F_rdv[0,1],0],[0,F_rdv[1,0],F_rdv[1,0]+F_rdv[1,1],F_rdv[1,1],0], linewidth=2, label='random diagonal')
axs.legend(['reference configuration','rotation','... + stretch'],loc='lower left')
plt.xlabel("$x_1$")
plt.ylabel("$x_2$")
plt.title('Polar Decomposition')
print('Rotation Tensor')
print('R =')
print(u)
print()
print()
print('Left Stretch Tensor')
print('v =')
print(v)
plt.show()