fig,axs=plt.subplots()
axs.axis('equal')
plt.plot([0,1,1,0,0],[0,0,1,1,0], linewidth=3, label='random diagonal')
plt.plot([0,F_dv[0,0],F_dv[0,0]+F_dv[0,1],F_dv[0,1],0],[0,F_dv[1,0],F_dv[1,0]+F_dv[1,1],F_dv[1,1],0], linewidth=2, label='random diagonal', linestyle='--')
plt.plot([0,F_drv[0,0],F_drv[0,0]+F_drv[0,1],F_drv[0,1],0],[0,F_drv[1,0],F_drv[1,0]+F_drv[1,1],F_drv[1,1],0], linewidth=2, label='random diagonal')
axs.legend(['reference configuration','stretch','... + rotation'],loc='lower left')
plt.xlabel("$x_1$")
plt.ylabel("$x_2$")
plt.title('Polar Decomposition')
print('Rotation Tensor')
print('R =')
print(R)
print()
print()
print('Right Stretch Tensor')
print('U =')
print(U)
plt.show()