fig,axs=plt.subplots()
axs.axis('equal')
plt.plot([0,1,1,0,0],[0,0,1,1,0], linewidth=3, label='random diagonal')
plt.plot([0,F_dr[0,0],F_dr[0,0]+F_dr[0,1],F_dr[0,1],0],[0,F_dr[1,0],F_dr[1,0]+F_dr[1,1],F_dr[1,1],0], linewidth=2, label='random diagonal', linestyle='--')
plt.plot([0,F_drv[0,0],F_drv[0,0]+F_drv[0,1],F_drv[0,1],0],[0,F_drv[1,0],F_drv[1,0]+F_drv[1,1],F_drv[1,1],0], linewidth=3, label='random diagonal')
axs.legend(['reference configuration','deviatoric stretch + rotation','... + change of volume'],loc='lower left')
plt.xlabel("$x_1$")
plt.ylabel("$x_2$")
plt.title('Volumetric Decomposition')
print('Volume Ratio')
print('J =')
print(np.linalg.det(U))
plt.show()