fig,axs=plt.subplots()
axs.axis('equal')
plt.plot([0,1,1,0,0],[0,0,1,1,0], linewidth=3, label='random diagonal')
plt.plot([0,F_rd[0,0],F_rd[0,0]+F_rd[0,1],F_rd[0,1],0],[0,F_rd[1,0],F_rd[1,0]+F_rd[1,1],F_rd[1,1],0], linewidth=2, label='random diagonal', linestyle='--')
plt.plot([0,F_rdv[0,0],F_rdv[0,0]+F_rdv[0,1],F_rdv[0,1],0],[0,F_rdv[1,0],F_rdv[1,0]+F_rdv[1,1],F_rdv[1,1],0], linewidth=3, label='random diagonal')
axs.legend(['reference configuration','rotation + deviatoric stretch','... + change of volume'],loc='lower left')
plt.xlabel("$x_1$")
plt.ylabel("$x_2$")
plt.title('Volumetric Decomposition')
print('Volume Ratio')
print('J =')
print(np.linalg.det(v))
plt.show()