fig,axs=plt.subplots()
axs.axis('equal')
plt.plot([0,1,1,0,0],[0,0,1,1,0], linewidth=3, label='random diagonal')
plt.plot([0,F_rd[0,0],F_rd[0,0]+F_rd[0,1],F_rd[0,1],0],[0,F_rd[1,0],F_rd[1,0]+F_rd[1,1],F_rd[1,1],0], linewidth=2, label='random diagonal', linestyle='--')
plt.plot([0,F_rdv[0,0],F_rdv[0,0]+F_rdv[0,1],F_rdv[0,1],0],[0,F_rdv[1,0],F_rdv[1,0]+F_rdv[1,1],F_rdv[1,1],0], linewidth=3, label='random diagonal')
#axs.legend(['reference configuration','rotation + change of shape','change of volume'],loc='lower left')
plt.xlabel("$x$")
plt.ylabel("$y$")
plt.title('Volumetric Decomposition')
print('J')
print(np.linalg.det(v))
plt.show()